Ullaakut/nmap

examples/count_hosts_by_os/main.go
examples_test.go
tests/xml/scan01.xml
xml.go
xml_test.go

As mentioned in #8 the ``osclass`` data is always empty. I checked the [nmap DTD XML specifications](https://nmap.org/data/nmap.dtd), in which it is stated that ``osclass`` is a child of ``osmatch``. Therefore I changed the xml.go accordingly and adapted the xml_test.go as well as the corresponding sample XML data. Additionally I extended the compareResults function in order ease debugging the new struct hierarchy.
As a last point I changed the ``TestToFile`` function to work os independent.
Best regards

Fix OSClass parsing

---

README.md
examples/basic_scan/main.go
examples/count_hosts_by_os/main.go
examples/service_detection/main.go
examples/spoof_and_decoys/main.go
xml.go
xml_test.go

go 1.11.x 
```shell
../../vendor/github.com/Ullaakut/nmap/xml.go:9:2: cannot find package "github.com/ullaakut/nmap/pkg/osfamilies" in any of:
/root/.jenkins/jobs/xxxx-2.13.x/workspace/src/idcos.io/xxxx/vendor/github.com/ullaakut/nmap/pkg/osfamilies (vendor tree)
/opt/golang/go/src/github.com/ullaakut/nmap/pkg/osfamilies (from $GOROOT)
/root/.jenkins/jobs/xxxx-2.13.x/workspace/src/github.com/ullaakut/nmap/pkg/osfamilies (from $GOPATH)
```

go install error

---

examples/basic_scan_async/main.go
nmap.go

This PR contains code changes to support RunAsync methods to allow for real time updates from the NMAP process. It is currently able to spit out XML results to the screen.
Fixes #6 
**TESTS**
Still need to be created.
**BUG**
When running in Async if you hit enter, it pulls a progress update from the the Nmap command. This is not intentional. I need to research into whether is is due to using bufio some how or what is cause this.
If `scanner.GetStdout` or `scanner.GetStderr` or `scanner.Wait` are called before the command `scanner.RunAsync` is ran, errors will occur. This may be the reason channels are a better approach. 
@Ullaakut Thoughts?
**FUTURE**
Look into creating a custom XML Decoder to read XML as it is received. This would allow realtime updates to be converted into structs for …

RunAsync function with supporting struct changes

---

nmap.go
nmap_test.go

It appears the Nmap library is missing the `--stats-every` option offered by Nmap. This command should be implemented to support additional functionality, especially with the addition of the `RunAsync` command.
Additionally this options allows things such as the below to be more streamline..
[Nmap Asynchronous Progress Stream](https://asciinema.org/a/AVdF5M00bwgeJXCWrMLXAtItE)

Added nmap --stats-every option

---

nmap.go
nmap_test.go

WithVerbosity and WithDebugging. Additionally updating nmap_test with proper tests.
See issue:
https://github.com/Ullaakut/nmap/issues/30

Adding nmap options for verbosity and debugging

---

xml.go
xml_test.go

I desired the ability to extract the XML results without having to deal with the filesystem, so I added a method to extract them via `io.Reader`.
I wasn't sure if you were interested in adding a method like this, but I figured I would at least give you the option of adding it.

Added ToReader method for streaming out XML results

---

nmap.go
nmap_test.go

Hi,
I modified the function "WithPorts" for type Scanner. This will get around the error:
`[Only 1 -p option allowed, separate multiple ranges with commas. QUITTING! EOF]`
Also modified _nmap_test.go_ to check if the new function works.
best regards

Fix multiple with port calls

---

README.md
go.mod
go.sum
xml_test.go

Even with the v2 module (thanks!), the projects that pull this as dependency still show the previous version as indirect dependency (which is slightly confusing - "why is it still there?") due to the test having the old import.  This PR changes the import in xml_test.go to the `/v2` one, and also updates the documentation badge to point to pkg.go.dev - I believe godoc.org doesn't support the version > v2.
I would appreciate if you could cut yet another (v2.0.2) release after you merge this 😄 
Fixes #57

modify test dependency to /v2, update doc badge

---

.travis.yml
examples/basic_scan_streamer_interface/main.go
go.mod
go.sum
nmap.go
nmap_test.go

Hi,
I fixed the function RunWithProgress because there was a memory leak (line 212) when cancelling the context before the scan was finished.
I also added a new "Run" type of funtion (RunWithStreamer) that writes the xml-output directly to a file.
- This will prevent huge memory usage when running long scans.
- It also enables the standard nmap output to monitor the current nmap status.
- When the scan is finished the file can be parsed.
There is also an example showing how to run this type of scan.
Best regards!
P.S.
I would also appreciate a new tag :-)

Fix run with progress and add new Run function

---

nmap.go

Hi @Ullaakut
This should add what I miss in the issue #86
Regards

Add print and return args, fix #86

---

iflist_test.go
nmap.go
nmap_test.go

Fixes #97 
Adds support for the flags found at:
* [`--unique`](https://nmap.org/book/man-target-specification.html)
* [`--script-timeout`](https://nmap.org/book/man-performance.html)
And adds unit tests.

Add --unique and --script-timeout flags

---

nmap.go

This PR adds support for modifying the exec.Cmd instance

Add modifyCmdFunc to Scanner and WithModifyCmdFunc option

---

nmap.go

Since nmap defaults to writing the normal nmap output to stdout, there is no need to force it when writing the XML output to a file.

Not forcing normal nmap output to stdout

---

optionsOutput.go
optionsOutput_test.go

Add   --noninteractive 
issue #113

Add no interactions to list of output args

---

tests/xml/scan_base.xml
xml.go
xml_test.go

Hello, 
Here is a small PR that adds a missing field in the `Host` struct so that we can use that field in go code. My goal is to be able to differentiate between a successful complete scan and a partial scan with timeouts.
In version [Nmap 7.92 [2021-08-07]](https://nmap.org/changelog.html#7.92) a new xml attribute was added to the <Host> tag.
See link to [changelog](https://nmap.org/changelog.html#7.92:~:text=If%20a%20host%20times%20out%2C%20the%20XML%20%3Chost%3E%20element%20will%20have%20the%20attribute%20timedout%3D%22true%22%20and%20the%20host%27s%20timing%20info%20(srtt%20etc.)%20will%20still%20be%20printed.) 
```
If a host times out, the XML <host> element will have the attribute timedout="true" and the host's timing info (srtt etc.) will still be printed.
```
This field is only …

Add Host timedout field

---

nmap.go
nmap_test.go

This is a fix for https://github.com/Ullaakut/nmap/issues/122
According to golang standard library documentation in https://pkg.go.dev/os/exec#Cmd.StdoutPipe
> It is thus incorrect to call Wait before all reads from the pipe have completed
And in https://github.com/Ullaakut/nmap/blob/a7503243d25b206a78311f83a66ecd55bb5e36fe/nmap.go#L149 this is exactly what is done. `Wait` is called while `io.Copy` ([[1]](https://github.com/Ullaakut/nmap/blob/a7503243d25b206a78311f83a66ecd55bb5e36fe/nmap.go#L132) , [[2]](https://github.com/Ullaakut/nmap/blob/a7503243d25b206a78311f83a66ecd55bb5e36fe/nmap.go#L136C6-L136C13)) is still performing reads on `stdoutDuplicate`.
The fix is inspired from a solution to a [similar simplified problem](https://github.com/golang/go/issues/38268#issuecomment-609562062) …

Fix unable to parse nmap output for incomplete XML output

---

nmap.go

When using the live progress with big subnets, at some point the memory will rise very high.
Sometimes up to Gigabytes.
By moving the declaration of the progress variable into the loop this is fixed and the memory will stay in the low Megabytes.

Fixed memory leak when using live progress

---

examples_test.go

Removes outdated test which relied on google.com and facebook.com having specific ports closed instead of filtered which is no longer the case. Was obviously dumb in retrospect 🤷 
Will then fix #134 by publishing a new version.

fix: remove outdated example test

---

errors.go
nmap.go

Improve error handling when `WithOSDetection` is called without being root
https://gist.github.com/tonymet/6107b994863d8ba8f6e0c062ae026b27
```
git clone git@gist.github.com:6107b994863d8ba8f6e0c062ae026b27.git node-go-test
cd node-go-test
go run . --target 192.168.10.1 
2025/01/04 17:21:09 unable to run nmap scan: this feature requires root privileges
2025/01/04 17:21:09 Warnings: 
&[TCP/IP fingerprinting (for OS scan) requires root privileges.]
Nmap done: 0 hosts up scanned in 0.000000 seconds
```
1. create a scanner WithOSDetection() (see gist)
2. inspect err or warnings
```
scanner, err := nmap.NewScanner(
ctx,
nmap.WithTargets(optTargets...),
nmap.WithPorts(optPorts),
nmap.WithOSDetection(),
)
```
```
2025/01/04 17:15:08 unable to run nmap scan: exit status 1
```
```
2025/01/04 …
```

WithOSDetection: check for root privileges warning -- fix unclear error status

---

errors.go
nmap.go

- Re-wired ErrScanTimout which was left unused since prior code changes
- Added ErrScanInterrupt which is now returned on ctrl+c or programmatically triggered interrupts (cancelled contexts). This is useful to distinguish interrupt exit codes from others during error handling.

Improved returned errors

---

errors.go
nmap.go

Had to change it again, I got mislead by a deceptive code inspection message of my IDE. I was wondering already, why it would say `errStatus` cannot be nil, obviously it can and even should. 
It seems the IDE was deriving this annotation based on my case statement above, like "Okay, you do not check for nil, so I guess it won't be nil", rather then looking at what could really arrive through the `done` channel... 🤷‍♂️
Obviously, `errStatus` CAN be nil and the call of `.Error()` in the case clauses would make the latest changes ballistic :)
I had to divide the cases up again:

Fixed issue with latest return error handling
